package com.example.springbootapp.model;

import com.example.springbootapp.models.ProductModel;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class ProductModelTest {

    @Test
    public void testGettersAndSetters() {
        // Criando uma instância do modelo de produto
        ProductModel productModel = new ProductModel();

        // Criando valores de teste
        UUID id = UUID.randomUUID();
        String name = "Test Product";
        BigDecimal value = BigDecimal.valueOf(19.99);

        // Usando os setters
        productModel.setIdProduct(id);
        productModel.setName(name);
        productModel.setValue(value);

        // Verificando se os getters retornam os valores corretos
        assertEquals(id, productModel.getIdProduct());
        assertEquals(name, productModel.getName());
        assertEquals(value, productModel.getValue());
    }

    @Test
    public void testNoArgsConstructor() {
        // Testando o construtor sem argumentos
        ProductModel productModel = new ProductModel();

        // Verificando se a instância não é nula
        assertNotNull(productModel);

        // Verificando os valores iniciais dos atributos
        assertNotNull(productModel.getIdProduct());
    }

    @Test
    public void testIdAutoGenerated() {
        // Testando a geração automática de ID
        ProductModel productModel = new ProductModel();
        assertNotNull(productModel.getIdProduct());
    }
}